/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/StackNavigator`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/AuthContext`; params?: Router.UnknownInputParams; } | { pathname: `/auth/Auth_Api`; params?: Router.UnknownInputParams; } | { pathname: `/auth/UserContext`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Activity`; params?: Router.UnknownInputParams; } | { pathname: `/screens/ChangeUserNameScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Friends`; params?: Router.UnknownInputParams; } | { pathname: `/screens/HomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/IntroScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Leaderboard`; params?: Router.UnknownInputParams; } | { pathname: `/screens/LoadingScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/SignUpScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/SplashScreen`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/StackNavigator`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/AuthContext`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/Auth_Api`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/UserContext`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/Activity`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/ChangeUserNameScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/Friends`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/HomeScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/IntroScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/Leaderboard`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/LoadingScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/LoginScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/SignUpScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/SplashScreen`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/StackNavigator${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/auth/AuthContext${`?${string}` | `#${string}` | ''}` | `/auth/Auth_Api${`?${string}` | `#${string}` | ''}` | `/auth/UserContext${`?${string}` | `#${string}` | ''}` | `/screens/Activity${`?${string}` | `#${string}` | ''}` | `/screens/ChangeUserNameScreen${`?${string}` | `#${string}` | ''}` | `/screens/Friends${`?${string}` | `#${string}` | ''}` | `/screens/HomeScreen${`?${string}` | `#${string}` | ''}` | `/screens/IntroScreen${`?${string}` | `#${string}` | ''}` | `/screens/Leaderboard${`?${string}` | `#${string}` | ''}` | `/screens/LoadingScreen${`?${string}` | `#${string}` | ''}` | `/screens/LoginScreen${`?${string}` | `#${string}` | ''}` | `/screens/SignUpScreen${`?${string}` | `#${string}` | ''}` | `/screens/SplashScreen${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/StackNavigator`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/AuthContext`; params?: Router.UnknownInputParams; } | { pathname: `/auth/Auth_Api`; params?: Router.UnknownInputParams; } | { pathname: `/auth/UserContext`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Activity`; params?: Router.UnknownInputParams; } | { pathname: `/screens/ChangeUserNameScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Friends`; params?: Router.UnknownInputParams; } | { pathname: `/screens/HomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/IntroScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Leaderboard`; params?: Router.UnknownInputParams; } | { pathname: `/screens/LoadingScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/SignUpScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/SplashScreen`; params?: Router.UnknownInputParams; };
    }
  }
}
